// Random reappearance at screened edge positions, with no relocation during use.
const agentWidget=document.querySelector('.agent-widget');
let agentMoveTimer,agentPosition=null,agentTeleporting=false,agentCycle=0;
function edgePositions(){const margin=innerWidth<=760?16:25;const size=launcher.offsetWidth;const headerBottom=document.querySelector('.site-header').getBoundingClientRect().bottom;const top=Math.max(margin,headerBottom+18);const bottom=innerHeight-margin-size;const middle=(top+bottom)/2;return [top,middle,bottom].flatMap((y,i)=>[{x:margin,y,side:'left',row:i},{x:innerWidth-margin-size,y,side:'right',row:i}]).filter(p=>p.y>=margin&&p.y+size<=innerHeight-margin);}
function clearPosition(){agentPosition=null;agentWidget.style.left='auto';agentWidget.style.top='auto';agentWidget.style.right='';agentWidget.style.bottom='';agentWidget.style.transform='none';document.body.classList.remove('agent-left');}
function positionAgent(){if(!agentPosition)return;const points=edgePositions();const replacement=points.find(p=>p.side===agentPosition.side&&p.row===agentPosition.row)||points.at(-1);if(!replacement){clearPosition();return;}agentPosition=replacement;agentWidget.style.left=replacement.x+'px';agentWidget.style.top=replacement.y+'px';agentWidget.style.right='auto';agentWidget.style.bottom='auto';agentWidget.style.transform='none';document.body.classList.toggle('agent-left',replacement.side==='left');}
function agentBusy(){return !agentWindow.hidden||agentWidget.matches(':hover')||agentWidget.contains(document.activeElement)||document.activeElement.matches('input,textarea,select')||document.hidden;}
function safePosition(p){const size=launcher.offsetWidth,pad=12;const overlaps=r=>p.x-pad<r.right&&p.x+size+pad>r.left&&p.y-pad<r.bottom&&p.y+size+pad>r.top;return ![...document.querySelectorAll('a,button,input,textarea,select')].filter(el=>!agentWidget.contains(el)&&el.getClientRects().length).some(el=>overlaps(el.getBoundingClientRect()));}
function delay(ms){return new Promise(resolve=>setTimeout(resolve,ms));}
async function moveAgent(){if(!motionToggle.checked||reduced.matches||agentBusy()||agentTeleporting)return false;const old=launcher.getBoundingClientRect();const choices=edgePositions().filter(p=>Math.hypot(p.x-old.x,p.y-old.y)>100&&safePosition(p));if(!choices.length)return false;const selected=choices[Math.floor(Math.random()*choices.length)];const cycle=++agentCycle;agentTeleporting=true;agentWidget.classList.add('vanishing');await delay(620);
 if(cycle!==agentCycle)return false;
 if(!motionToggle.checked||reduced.matches||agentBusy()){agentWidget.classList.remove('vanishing');agentTeleporting=false;return false;}
 agentWidget.classList.remove('vanishing');agentPosition=selected;positionAgent();agentWidget.classList.add('reappearing');await delay(850);if(cycle!==agentCycle)return false;agentWidget.classList.remove('reappearing');agentTeleporting=false;return true;}
function scheduleAgent(){clearTimeout(agentMoveTimer);if(motionToggle.checked&&!reduced.matches){agentMoveTimer=setTimeout(async()=>{await moveAgent();scheduleAgent();},35000+Math.random()*20000);}else{++agentCycle;agentTeleporting=false;agentWidget.classList.remove('vanishing','reappearing');clearPosition();fitAgentWindow();}}
function fitAgentWindow(){if(agentWindow.hidden)return;const bubble=launcher.getBoundingClientRect();const margin=16;agentWindow.style.right='auto';agentWindow.style.bottom='auto';agentWindow.style.left='0px';agentWindow.style.top='0px';const r=agentWindow.getBoundingClientRect();const x=Math.min(Math.max(margin,bubble.x),Math.max(margin,innerWidth-r.width-margin));const desired=bubble.y<innerHeight/2?bubble.bottom+12:bubble.y-r.height-12;const y=Math.min(Math.max(margin,desired),Math.max(margin,innerHeight-r.height-margin));agentWindow.style.left=x-bubble.x+'px';agentWindow.style.top=y-bubble.y+'px';}
const agentWindowObserver=new MutationObserver(()=>fitAgentWindow());agentWindowObserver.observe(agentWindow,{attributes:true,attributeFilter:['hidden']});
function stopTeleport(){if(agentTeleporting){++agentCycle;agentTeleporting=false;agentWidget.classList.remove('vanishing','reappearing');}}
agentWidget.addEventListener('pointerenter',stopTeleport);agentWidget.addEventListener('focusin',stopTeleport);
motionToggle.addEventListener('change',scheduleAgent);reduced.addEventListener('change',scheduleAgent);addEventListener('resize',()=>{positionAgent();fitAgentWindow();});scheduleAgent();
window.previewAgentMove=moveAgent;
