const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const base=process.env.TEST_URL||'http://127.0.0.1:8015/';const b=await chromium.launch();try{
 for(const width of [320,390,1280]){const p=await b.newPage({viewport:{width,height:900},reducedMotion:'reduce'});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(base);
 assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.equal(await p.locator('#projects article').count(),6);assert.equal(await p.locator('.card-media img').count(),15);
 for(const img of await p.locator('.card-media img').all()){await img.scrollIntoViewIfNeeded();await img.evaluate(el=>el.decode());}
 for(const name of ['CV.pdf','CV_Zoyem_Roslin_Kenne_Cybersecurite.pdf']){const r=await p.request.get(new URL(name,base).href);assert.equal(r.status(),200);assert.equal((await r.body()).subarray(0,4).toString(),'%PDF');}
 const texts=await p.evaluate(()=>Object.fromEntries(['about','experience','skills','education','certifications','projects','contact'].map(k=>[k,document.getElementById(k).textContent.replace(/\s+/g,' ').trim()])));
 await p.locator('#agent-launcher').click();await p.locator('[data-agent="projects"]').click();assert.equal(await p.locator('.agent-message').count(),3);await p.keyboard.press('Escape');assert.ok(!await p.locator('#agent-window').isVisible());assert.equal(await p.locator('#motion').isChecked(),false);
 await p.locator('[data-tool="dmarc"]').click();assert.match(await p.locator('#tool-title').innerText(),/courriel/);
 let sent=false;await p.route('https://formspree.io/**',async route=>{assert.equal(route.request().method(),'POST');sent=true;await route.fulfill({status:200,contentType:'text/html',body:'Envoi intercepté par le test'});});await p.locator('#contact-name').fill('Test local');await p.locator('#contact-email').fill('local@example.test');await p.locator('#contact-message').fill('Test sans envoi réel');await p.locator('#contact form button').click();await p.waitForURL('https://formspree.io/**');assert.ok(sent);
 await p.route('https://fonts.googleapis.com/**',r=>r.abort());await p.goto(new URL('archives/2026-10-02/',base).href,{waitUntil:'domcontentloaded'});const archived=await p.evaluate(()=>Object.fromEntries(['about','experience','skills','education','certifications','projects','contact'].map(k=>[k,document.getElementById(k).textContent.replace(/\s+/g,' ').trim()])));assert.deepEqual(texts,archived);assert.deepEqual(errors,[]);await p.close();console.log('Validated publication and archive at '+width+'px');
 }
 const p=await b.newPage({javaScriptEnabled:false,viewport:{width:390,height:900}});await p.goto(base);assert.ok(await p.locator('#projects').isVisible());assert.ok(await p.locator('.site-header a[href="#projects"]').isVisible());assert.ok(await p.locator('#contact form').isVisible());await p.close();console.log('Content and navigation available without JavaScript');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
